### ISSUE TITLE
Put the package on npm?

### ISSUE THREAD

**Issue by pavelkucera** [pinojs/pino-filter#2]
Hi,

If I am not mistaken, this library is not on npm right now. Would you please put it there?

Pavel

**Comment by jsumners** [comment]
I don't think this ever got to a point where I considered it release ready. At this point, it should probably be re-written to take advantage of the prettifier API in the upcoming pino@5 release.

@pavelkucera if you are using this and find it helpful, would you be willing to pick up the maintenance of it? I just do not have the time and have honestly never even used it.

**Comment by pavelkucera** [comment]
I apologize for such a late response, I was dealing with exams. Unfortunately, I just found it via a Google search and it seemed useful, I haven't used it so I'm probably not the best candidate for maintaining the library.

**Comment by Fdawgs** [comment]
Seems to be on NPM now, so this can be closed as completed. :)
