### ISSUE TITLE
pino-filter under bun is buffering

### ISSUE THREAD

**Issue by koo5** [pinojs/pino-filter#65]
i am running something like ```tail -f logfile | bun ./node_modules/pino-filter/index.js -- `pwd`/pino-filter.json```
(using `./node_modules/pino-filter/index.js` as per the workaround in the other issue). 

But the output is buffered. Works fine with node. Not sure what's to blame.

**Comment by jsumners** [comment]
Thank you for the report. This project targets the [Node.js](https://nodejs.org) runtime. If you are encountering issues using Bun, please file issues there as [requested by them](https://twitter.com/jarredsumner/status/1700497869160268155).
